version: "2"

plugins:
  editorconfig:
    enabled: true
  eslint:
    enabled: true
    channel: "eslint-7"
  fixme:
    enabled: true
  markdownlint:
    enabled: true
  nodesecurity:
    enabled: true

exclude_patterns:
- "**/dist/"
- "**/browser/"
- "**/node_modules/"
- "**/script/"
- "**/spec/"
- "**/test/"
- "**/tests/"
- "**/vendor/"
- "**/*_test.go"
- "**/*.d.ts"
- "**/views/"
- "**/src/routes/"
- "**/schemas/"
- "**/*.test.*"
- "**/packages/irc2as/"
- "**/packages/sockethub-platform-feeds/"
- "**/packages/activity-streams.js/"
- "**/packages/sockethub-platform-irc/"
- "**/packages/sockethub-schemas/"
