version: "2"

plugins:
  editorconfig:
    enabled: true
  eslint:
    enabled: true
    channel: "eslint-7"
  fixme:
    enabled: true
  markdownlint:
    enabled: true
  nodesecurity:
    enabled: true

exclude_patterns:
- "**/dist/"
- "**/browser/"
- "**/node_modules/"
- "**/test/"
- "**/*.d.ts"
- "**/*.test.*"
- "packages/server/views/examples/"
- "packages/schemas/schemas/"
- "packages/irc2as/"
- "packages/platform-feeds/"
- "packages/activity-streams.js/"
- "packages/platform-irc/"
- "packages/platform-xmpp/"
